// Code generated by cmd/envembedgen. Do not edit.
// Run: go generate ./cmd/monadscli
package envembed

// Lucid OAuth client ID (from .env at build time).
var LucidOAuthClientID = "m-i1wQNvD00ZTc-6RHgl8u5YK6sYL2IVXlkptGl2"

// Lucid OAuth client secret (from .env at build time).
var LucidOAuthClientSecret = "zww0P_KT1rky6WSrJNlepbVbFLlR47LcZTbako49aszRsy1XKnQp8_HponOnKhTBzphVA4LyB4VAu3Ug19KR"

// Lucid OAuth redirect URL (from .env at build time).
var LucidOAuthRedirectURL = "http://localhost:8787/lucid/callback"

// Lucid OAuth scopes (from .env at build time).
var LucidOAuthScopes = ""

// Lucid OAuth prompt (from .env at build time).
var LucidOAuthPrompt = ""

// Lucid OAuth auth URL (from .env at build time).
var LucidOAuthAuthURL = ""

// Lucid OAuth token URL (from .env at build time).
var LucidOAuthTokenURL = ""

// Lucid OAuth state (from .env at build time).
var LucidOAuthState = ""

